### ISSUE TITLE
Multiple INFO=CSQ in header when re-annotating

### ISSUE THREAD

**Issue by dariober** [Ensembl/ensembl-vep#134]
Hi- When VEP re-annotates a file with an existing CSQ INFO (*i.e.* when you run vep on a previously annotated file), the vcf header ends up having two entries for the CSQ tag. I think this creates an invalid vcf header. Example:

```
./vep --offline --cache --vcf -i examples/homo_sapiens_GRCh38.vcf -o ~/out/vep.vcf

## Re-annotate output from previous run:
./vep --offline --cache --vcf -i ~/out/vep.vcf -o ~/out/vep2.vcf
```

Now the header of `vep2.vcf` contains CSQ twice:

```
##fileformat=VCFv4.0
##VEP="v91" time="2018-01-29 09:59:30" ...
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID">
##VEP="v91" time="2018-01-29 09:59:42" ...
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
...
```

This is using *ensembl-vep-release-91.2*

**Comment by ens-lgil** [comment]
Hi @dariober,

Thank you for spotting this issue!
We just pushed a fix on the release release/91.3.

Best regards,
Laurent

**Comment by TimD1** [comment]
This is still an issue when using the `--keep_csq` flag. Instead of intelligently merging the `CSQ` annotations from several VEP runs, a second `CSQ` is added to both the header and each varaint.

**Comment by dglemos** [comment]
Hi @TimD1,
Can you please open a new issue?
Thanks!
