### ISSUE TITLE
--shift_hgvs wrong output?

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#236]
Hi,
I've run such command:

vep -i test.indels.vcf --cache **--refseq** -o test_out_1_.tsv  --port 3337 --tab --exclude_predicted --ASSEMBLY GRCh37 --sift b --polyphen b --humdiv --ccds --uniprot --symbol --numbers --domains --regulatory --canonical --protein --biotype --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --variant_class -custom /home/vep/DATA/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF -custom /home/vep/DATA/gnomAD/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz,gnomADg,vcf,exact,0,AF_NFE,POPMAX,AF --use_transcript_ref --hgvs --hgvsg --no_escape **--fasta /home/vep/refs/hs37d5.fa** --plugin dbscSNV,/home/vep/DATA/dbscSNP/dbscSNV1.1_GRCh37.txt.gz --plugin SpliceRegion --plugin MaxEntScan,/home/vep/DATA/MaxEntScan --plugin GeneSplicer,/home/vep/DATA/GeneSplicer/sources/genesplicer,/home/vep/DATA/GeneSplicer/human --plugin ExACpLI,/home/vep/DATA/ExACpLI/ExACpLI_values.txt --plugin REVEL,/home/vep/DATA/revel/revel_all_chromosomes.csv --plugin LoFtool,/home/vep/DATA/LoFtool/LoFtool_scores.txt --plugin Phenotypes --plugin G2P,file=/home/vep/DATA/G2P/DDG2P.csv.gz --format "vcf" --fork 1 **--shift_hgvs 0**

then I've run it again, but **--shift_hgvs 1**

My input file is kind of a "mock file", for testing purposes, it looks like this:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  XXXX
1       866511  testID  C       CCCCT   .       .       .       GT      0/1
```
both, `--shift_hgvs 0` and `--shift_hgvs 1` return the same result:
```
#Uploaded_variation	Location	Allele	HGVS_OFFSET	HGVSg
testID	1:866511-866512	CCCT	15	1:g.866523_866526dup
```

shouldn't the offset=15 disappear when using --shift_hgvs 0 ?

**Comment by ens-lgil** [comment]
Dear @thedam,

Thank you for reporting this issue!
The output column "HGVS_OFFSET" is always displayed with the flag `--hgvs`, but its value should be 0 if there is no 3 prime shift (or the flag `--shift_hgvs` is set to 0).
However it looks like the flag `--shift_hgvs` is not working properly.
We are currently investigating it.

Best regards,
Laurent

**Comment by thedam** [comment]
I think I understand the meaning of shift, but there's always chance I interpret it wrong.
The picture is better then hundred words; it would be nice if you add some example how this shifting is done. A similar example like you here https://www.ensembl.org/info/docs/tools/vep/vep_formats.html,
VCF input: 
`20   2   .   TC   T   .   PASS   .`
VEP output:
`20   3   3   C/-   +`
(here I clearly see how the shift was done)

Thanks :)

**Comment by ens-lgil** [comment]
Dear @thedam,

We definitively need to add more examples.
We released a blog post last month talking about the normalisation of the allele reporting, which describes a bit what we do with the HGVS shifting: [http://www.ensembl.info/2018/06/22/cool-stuff-the-vep-can-do-normalisation/](http://www.ensembl.info/2018/06/22/cool-stuff-the-vep-can-do-normalisation/).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @thedam,

We pushed a fix on the version 92 and 93 (just released today).
Let us know if you still find some issues with this flag.

Best regards,
Laurent

**Comment by janrehker** [comment]
Hello everyone,

Sorry for bringing this issue up again... It seems this bug still exists

Here is my command:
vep -id '10 89711987  . CTA C' --offline --tab --hgvs --force_overwrite --dir Data/miniconda3/envs/vep2/.vep/ --assembly GRCh37 --refseq --fasta /home/rehkerj/Data/miniconda3/envs/vep2/.vep/homo_sapiens/101_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --shift_hgvs 0 --symbol

This is my output:
## ENSEMBL VARIANT EFFECT PREDICTOR v101.0
## Output produced at 2020-11-03 17:45:41
## Using cache in Data/miniconda3/envs/vep2/.vep/homo_sapiens_refseq/101_GRCh37
## Using API version 101, DB version ?
## ensembl-funcgen version 101.b918a49
## ensembl version 101.856c8e8
## ensembl-variation version 101.50e7372
## ensembl-io version 101.943b6c2
## assembly version GRCh37.p13
## gencode version GENCODE 19
## COSMIC version 90
## regbuild version 1.0
## HGMD-PUBLIC version 20194
## genebuild version 2011-04
## refseq version 01_2015
## ESP version 20141103
## sift version sift5.2.2
## dbSNP version 153
## polyphen version 2.2.2
## 1000genomes version phase3
## gnomAD version r2.1
## ClinVar version 201912
## Column descriptions:
## Uploaded_variation : Identifier of uploaded variant
## Location : Location of variant in standard coordinate format (chr:start or chr:start-end)
## Allele : The variant allele used to calculate the consequence
## Gene : Stable ID of affected gene
## Feature : Stable ID of feature
## Feature_type : Type of feature - Transcript, RegulatoryFeature or MotifFeature
## Consequence : Consequence type
## cDNA_position : Relative position of base pair in cDNA sequence
## CDS_position : Relative position of base pair in coding sequence
## Protein_position : Relative position of amino acid in protein
## Amino_acids : Reference and variant amino acids
## Codons : Reference and variant codon sequence
## Existing_variation : Identifier(s) of co-located known variants
## IMPACT : Subjective impact classification of consequence type
## DISTANCE : Shortest distance from variant to transcript
## STRAND : Strand of the feature (1/-1)
## FLAGS : Transcript quality flags
## SYMBOL : Gene symbol (e.g. HGNC)
## SYMBOL_SOURCE : Source of gene symbol
## HGNC_ID : Stable identifer of HGNC gene symbol
## REFSEQ_MATCH : RefSeq transcript match status
## REFSEQ_OFFSET : HGVS adjustment length required due to mismatch between RefSeq transcript and the reference genome
## GIVEN_REF : Reference allele from input
## USED_REF : Reference allele as used to get consequences
## BAM_EDIT : Indicates success or failure of edit using BAM file
## HGVSc : HGVS coding sequence name
## HGVSp : HGVS protein sequence name
## HGVS_OFFSET : Indicates by how many bases the HGVS notations for this variant have been shifted
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      IMPACT  DISTANCE        STRAND  FLAGSSYMBOL   SYMBOL_SOURCE   HGNC_ID REFSEQ_MATCH    REFSEQ_OFFSET   GIVEN_REF       USED_REF        BAM_EDIT        HGVSc   HGVSp   HGVS_OFFSET
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_000314.8     Transcript      frameshift_variant      1451-1452       606-607 202-203 TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene   -rseq_mrna_match -       TA      AT      -       NM_000314.8:c.607_608del        NP_000305.3:p.Ile203SerfsTer39  1
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_001304717.5  Transcript      frameshift_variant      1450-1451       1125-1126       375-376 TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene    -       rseq_mrna_nonmatch,rseq_cds_mismatch    -       TA      AT      FAILED  NM_001304717.5:c.1126_1127del   NP_001291646.4:p.Ile376SerfsTer39       1
10_89711988_TA/-        10:89711988-89711989    -       5728    NM_001304718.2  Transcript      frameshift_variant      1564-1565       15-16   5-6     TI/TX   acTAtt/actt     -       HIGH    -       1       -       PTEN    EntrezGene   -rseq_mrna_nonmatch,rseq_5p_mismatch     -1      TA      AT      OK      NM_001304718.2:c.16_17del       NP_001291647.1:p.Ile6SerfsTer39 1


It looks like vep ist still (or once more) commited to the shift..


Best regards,
Jan
