### ISSUE TITLE
Can't locate Try/Tiny.pm in @INC

### ISSUE THREAD

**Issue by jejacobs23** [Ensembl/ensembl-vep#737]
## Describe the issue
I'm trying to install and run VEP for the first time and I get an error when running it that states "Can't locate Try/Tiny.pm in @INC".  Initially, I had some difficulties with the installation and had to use the --NO_HTSLIB option.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 99
- VEP Cache version: 99
- Perl version: v5.15.3
- OS: CentOS 7.5.1804
- tabix installed ?: I'm not sure

### Full VEP command line
```
srun $VEP_DIR/vep -i $INPUT_FILE --cache --CACHEDIR $CACHE_DIR --force_overwrite --sift b -o $OUTPUT_DIR/VEP_prefiltered.txt
```

### Full error message
```
Can't locate Try/Tiny.pm in @INC (@INC contains: /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Feature.pm line 85.
srun: error: exanode-2-45: task 0: Exited with exit code 2
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Feature.pm line 85.
Compilation failed in require at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
Compilation failed in require at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
Compilation failed in require at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
Compilation failed in require at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
Compilation failed in require at (eval 3) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at (eval 2) line 2.
        ...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/vep line 20.
BEGIN failed--compilation aborted at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/vep line 20.
```

**Comment by aparton** [comment]
Hi,

Thanks for this report - installing the perl module Try::Tiny should resolve this issue. This can be done by running the command:

`cpanm Try::Tiny` (if you have cpan-minus installed, otherwise you can run `cpan Try::Tiny` and follow the instructions)

Let me know if this resolves your issue, and if not we'll take a closer look.

Kind Regards,
Andrew

**Comment by jejacobs23** [comment]
Thank you so much for your reply.  I tried `cpanm Try::Tiny` and got the following warning:

```
[jacojam@exahead1 modules]$ srun cpanm Try::Tiny
!
! Can't write to /usr/local/share/perl5 and /usr/local/bin: Installing modules to /home/users/jacojam/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl5 and /usr/local/bin)
!   - Configure local::lib your existing local::lib in this shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on Try::Tiny
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz ... OK
Configuring Try-Tiny-0.30 ... OK
Building and testing Try-Tiny-0.30 ... OK
Successfully installed Try-Tiny-0.30
1 distribution installed

```
I was able to locate the installed module in /home/users/jacojam/perl5, but when I run VEP, I still get the same error message 
```
Can't locate Try/Tiny.pm in @INC (@INC contains: /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Feature.pm line 85.
```

I will say that I'm using a cluster computing environment and I don't have root access so it may be an issue of the module not being installed in the proper location.  Looking at the warning message, I could try and configuring local::lib or installing local::lib using the suggested cpanm command.  However, this is above my level of experience and I'd appreciate some advice on what you think is the best course of action.

Thanks.

**Comment by aparton** [comment]
Hi,

If the module has been installed locally (and directly in the `/home/users/jacojam/perl5` folder and not any subdirectories), then you should be able to add its directory to your $PERL5LIB variable and VEP should find it from there. If you run:

`export PERL5LIB=${PERL5LIB}:/home/users/jacojam/perl5`

And then try running VEP again then it should pick it up. If it's been installed in a subdirectory, pointing PERL5LIB to that subdirectory should fix the issue. If not, could you please send me the file location of Try::Tiny, and the output of `echo $PERL5LIB?

Thanks,
Andrew

**Comment by jejacobs23** [comment]
OK.  That worked!  The module was in `/home/users/jacojam/perl5/lib/perl5` so I added that to the PERL5LIB environment variable as instructed.  

```
export PERL5LIB=${PERL5LIB}:/home/users/jacojam/perl5/lib/perl5
```

Then VEP failed due to not being able to access tabix so I located it (previously installed from htslib) and added it to my PATH environment variable.  

```
export PATH=${PATH}:/home/exacloud/lustre/jjacobs/programs/htslib-1.10.2
```

Now, VEP is failing due to the following error:
```
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (@INC contains: /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/modules /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep /home/users/jacojam/perl5/lib/perl5/x86_64-linux-thread-multi /home/users/jacojam/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 239) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, SQLite, Sponge.
 at /home/exacloud/lustre1/jjacobs/programs/VEP/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1770.
srun: error: exanode-2-45: task 0: Exited with exit code 2

```
I assume this is all part of the same issue stemming from installation in a cluster environment where I don't have root access, but it wasn't clear to me how to solve the mysql issue.  Should I try and install the perl module, mysql.pm?

Thanks again,

James.

**Comment by aparton** [comment]
Hi James, 

Assuming that you have mysql installed already on the cluster, then all you should need to do is install the perl module DBD::mysql in the same way as before.

Let me know how it goes, and if it doesn't work then I'll see what else we can do to help.

Kind Regards,
Andrew

**Comment by jejacobs23** [comment]
I tried that with the command cpanm DBD::mysql and got the following error:

```
!
! Can't write to /usr/local/share/perl5 and /usr/local/bin: Installing modules to /home/users/jacojam/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl5 and /usr/local/bin)
!   - Configure local::lib your existing local::lib in this shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-4.050.tar.gz ... OK
Configuring DBD-mysql-4.050 ... N/A
! Configure failed for DBD-mysql-4.050. See /home/users/jacojam/.cpanm/work/1587493620.60710/build.log for details.
srun: error: exanode-2-46: task 0: Exited with exit code 1
```
At the very end of the above file (build.log) this was the error message:

```
Checking if libs are available for compiling...
/home/users/jacojam/.cpanm/work/1587493620.60710/DBD-mysql-4.050/assertlibscR1i0Xq: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
wrong result: 'mysqlclient'
-> N/A
-> FAIL Configure failed for DBD-mysql-4.050. See /home/users/jacojam/.cpanm/work/1587493620.60710/build.log for details.
```

**Comment by jejacobs23** [comment]
Update:

I was able to fix the issue with the libmysqlclient.so.18.  Here is my understanding of this issue -

VEP has the ability to interact with the relational database, mysql.  However, if you use the --cache
option, you don't need this feature.  by adding the --offline flag in the VEP command line, you can 
run an analysis without having the perl module needed for relational databases.  This was the command-line that worked:

```
srun $VEP_DIR/vep -i $INPUT_FILE --offline --cache --dir_cache $CACHE_DIR --refseq --fasta $FASTA --force_overwrite --sift b -o $OUTPUT_DIR/VEP_prefiltered.txt
```

The --refseq flag indicates that I'm using the refseq annotations in my cache and the --fasta flag points to the hg38 fasta file.  This is needed when checking reference sequences when running in --offline mode.

Thanks so much for all your help with this!!

**Comment by aparton** [comment]
Hi @jejacobs23,

Glad to hear that you were able to resolve your issue. Your understanding of how our database/cache system works is correct - if you're interested then you can find more information about our cache files and databases here: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

I'm going to close this issue now, however if you have any more questions then please feel free to reopen it, or open a new issue.

Kind Regards,
Andrew
